name: Bandit Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  bandit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit and Fail on High Severity
        run: |
          bandit -r . --severity-level high -f json -o bandit-report.json || exit 1
          bandit -r . -f html -o bandit-report.html

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: bandit-security-reports
          path: |
            bandit-report.json
            bandit-report.html
